#!/bin/bash

# Since GeoKit uses Apple types on macOS, generating documentation on macOS
# doesn't produce useful documentation. Instead, generate the documentation
# on Linux where we define these types ourselves.

# Use `swift package plugin generate-documentation --help` for details

docker run -v $(PWD):/src --rm swift:6.0-noble /bin/sh -c 'cd /src; ./scripts/mgen'
