#!/bin/bash

# Since GeoKit uses Apple types on macOS, generating documentation on macOS
# doesn't produce useful documentation. Instead, generate the documentation
# on Linux where we define these types ourselves.

# Use `swift package plugin generate-documentation --help` for details

docker run -v $(PWD):/src --rm swift:6.0-noble /bin/sh -c 'cd /src; swift package generate-documentation --target GeoKit --disable-indexing --output-path docs --hosting-base-path /GeoKit/ --source-service github --source-service-base-url https://github.com/samalone/GeoKit/blob/main --checkout-path /src'
