#!/bin/bash

# Generate the documentation using macOS build tools.
# This is probably NOT what you want, since the whole point of GeoKit
# is to create Linux equivalents of macOS types, and these won't be
# included in the documentation. You should probably use "gen" instead.

# Since GeoKit uses Apple types on macOS, this command will generate
# incomplete documentation. Use the `gen` command to produce complete
# docs using Docker.

# Use `swift package plugin generate-documentation --help` for details

swift package \
    --allow-writing-to-directory docs \
    generate-documentation \
    --target GeoKit \
    --disable-indexing \
    --output-path docs \
    --hosting-base-path /GeoKit/ \
    --source-service github \
    --source-service-base-url https://github.com/samalone/GeoKit/blob/main \
    --checkout-path "$(PWD)"
